name: test

on: push

jobs:
  unittests:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run unit tests
        run: |
          device=$(xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//")
          xcodebuild test -scheme SwiftUINavController -destination "platform=iOS Simulator,name=$device"

  uitests:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run UI tests
        run: |
          cd SwiftUINavControllerExample
          device=$(xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//")
          xcodebuild test -scheme SwiftUINavControllerExample -destination "platform=iOS Simulator,name=$device"
